Change assignment during sub-module device alignment
huggingface/accelerate pull request #2058
Opened 2023-10-15 00:27 UTC by blbadger

# What does this PR do?

Fixes`peft` issue #868, https://github.com/huggingface/peft/issues/868

This PR addresses what appears to be a bug in the loading and merging/unloading of PeftModels.  

Background: After loading the necessary libraries,

```
!pip install -q -U bitsandbytes
!pip install -q -U git+https://github.com/huggingface/transformers.git
!pip install -q -U git+https://github.com/huggingface/peft.git
!pip install -q -U git+https://github.com/huggingface/accelerate.git
!pip install -q datasets==2.13.1 pyarrow==8.0.0 tokenizers==0.14.0 sentencepiece==0.1.99
```

attempting to call `PeftModel.from_pretrained()` on a model loaded using `device_map='auto'` as follows

```python
model = AutoModelForCausalLM.from_pretrained("emozilla/LLongMA-2-7b-flash", device_map='auto') 
lora_checkpoint = '/path/to/lora' # add path
model = PeftModel.from_pretrained(model, lora_checkpoint) 
```

results in many parameters being loaded as meta tensors with no data.  

Attempting to perform merging and unloading escapes explicit errors, but attempting to then load the merged model results in the error message "Cannot copy out of meta tensor; no data!" (`peft` issue #868).  This does not occur if `device_map='cpu'` is specified.

The root of the problem appears to be the choice to send module tensors to the "meta" device when enforcing a device alignment via `AlignDevicesHook` which would explain why it is present during LoRA application but typically not during the loading (and dispatching) of merged pretrained models.  

This PR allows for the loading and merging of LoRA parameters using the "auto" device map by assigning offloaded tensors to the CPU rather than the "meta" device. Doing so sends all sub-module tensors to one device (CPU) and thus aligns them, while saving the GPU memory that was specified by choosing the "auto" device map. 

Note that there may be good reason to recast offloaded parameters as meta tensors during device alignment, and if so I would be happy to work on an alternative approach to the problem.

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ x] Did you read the [contributor guideline](https://github.com/huggingface/accelerate/blob/main/CONTRIBUTING.md#submitting-a-pull-request-pr),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/accelerate/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/accelerate/tree/main/docs#writing-documentation---specification).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone!
@pacman100

2023-10-18 20:01 UTC, SunMarc reviewed
Hi @blbadger , as you suspected, we need to put the offloaded parameters to the `meta` device because we also need to consider for parameters that are offloaded on the disk. If we put all offloaded params on the cpu, we may get OOM. The problem our design is that we don't make the difference between cpu offload and disk offload when putting the parameters on `meta` device.

2023-10-22 16:02 UTC, blbadger commented
Thanks for clarifying @SunMarc! 

I have simplified the working tree and will work on preserving the cpu/disk distinction while sending parameters to the meta device.

2023-10-27 12:50 UTC, muellerzr requested changes
This still does not address what Marc mentioned. What would be a closer solution here is adding a param to `init_hook` (and the other hooks that set `"cpu"`) to include a default device to use, or explicit arg that is `cpu` which we can call at the higher levels. Because as a baseline the *init on meta should never change as a base case*.

2023-10-27 12:53 UTC, HuggingFaceDocBuilderDev commented
The docs for this PR live [here](https://moon-ci-docs.huggingface.co/docs/accelerate/pr_2058). All of your documentation changes will be reflected on that endpoint.

2023-10-29 00:31 UTC, blbadger commented
Understood @muellerzr, I can see why the default "meta" assignment should not change. 

After more thought it seems to me that the `peft` issue 868 is most elegantly addressed in that library itself rather than this one. The problem in that issue is really that the offloaded parameters are not re-loaded before merging and unloading, so I am working on a solution where each module calls the pre-forward device alignment hook to load parameters and then offloads again after merging to best maintain the original device alignment.

Therefore I would be happy to close this PR if that sounds good to everyone.

2023-10-31 12:18 UTC, muellerzr commented
Sounds good to me @blbadger!

2023-10-31 22:12 UTC, closed without merging