Fix batch_sampler maybe None error
huggingface/accelerate pull request #3025
Opened 2024-08-17 15:14 UTC by candlewill

# Fix batch_sampler maybe None error

Fixes # (issue)

https://github.com/huggingface/accelerate/issues/3011

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/accelerate/blob/main/CONTRIBUTING.md#submitting-a-pull-request-pr),
      Pull Request section?
- [x] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/accelerate/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/accelerate/tree/main/docs#writing-documentation---specification).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

- Core parts of the library: @BenjaminBossan

2024-08-19 13:33 UTC, BenjaminBossan commented
Thanks a lot for creating the PR. If you could also add a unit test to [`test_data_loader.py`](https://github.com/huggingface/accelerate/blob/main/tests/test_accelerator.py), that would be great. The test could basically be the same as the example you provided in the issue.

2024-08-19 15:17 UTC, muellerzr reviewed
agreed with Benjamin, let's add a test here then ✅ , thanks!

2024-08-19 15:21 UTC, HuggingFaceDocBuilderDev commented
The docs for this PR live [here](https://moon-ci-docs.huggingface.co/docs/accelerate/pr_3025). All of your documentation changes will be reflected on that endpoint. The docs are available until 30 days after the last update.

2024-08-20 15:02 UTC, candlewill commented
The unit test code is added, please help to review and merge.

2024-08-20 15:26 UTC, muellerzr approved these changes
Thanks! Overall this looks good to me, please run `pip install -e .[quality]; make style; make quality;` to fix the quality failures, and I made a comment for why the tests are failing

2024-08-20 15:26 UTC, muellerzr commented on tests/test_data_loader.py
> +    def test_iterable_dataset_using_none_batch_size():
This is part of a `unittest.TestCase`, so it needs `self`
```suggestion
    def test_iterable_dataset_using_none_batch_size(self):
```

2024-08-21 10:09 UTC, BenjaminBossan requested changes
Thanks for adding the test @candlewill. This PR is almost good to go, only the linter needs to be satisfied. This is because [these lines](https://github.com/huggingface/accelerate/pull/3025/files#diff-09bbe4f689c597ef1e168657171d49d91220c431c79f98983603ad7bc7551cb0R49-R60) are indented one level too far.

2024-08-22 07:38 UTC, candlewill commented
I am sure now everything is OK, please help review again.

2024-08-22 12:39 UTC, muellerzr approved these changes
Thanks for adding a test!

2024-08-23 00:02 UTC, merged